import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Headers from '@/modules/project/header'
import MainLayout from '@/layout/MainLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <MainLayout>
            <div className='flex flex-col w-full items-end bg-dark'>
                <Headers />
                <div className='w-full md:w-[79%] pb-28 relative'>
                    {children}
                </div>
            </div>
        </MainLayout>
    )
}
